import {
  NAVIGATION_ITEMS,
} from '../../appConfig' ;

// SIGNUP
const USERENTRYMENU_LINK1_URL = NAVIGATION_ITEMS.signup.link;
const USERENTRYMENU_LINK1_TEXT = NAVIGATION_ITEMS.signup.name;

// SIGNIN
const USERENTRYMENU_LINK2_URL = NAVIGATION_ITEMS.signin.link;
const USERENTRYMENU_LINK2_TEXT = 'Войти';

export {
  USERENTRYMENU_LINK1_TEXT,
  USERENTRYMENU_LINK1_URL,
  USERENTRYMENU_LINK2_TEXT,
  USERENTRYMENU_LINK2_URL,
};
